apiVersion: v1
kind: Service
metadata:
  name: demo-metrics-app
  labels:
    app: demo-metrics-app
spec:
  type: NodePort
  selector:
    app: demo-metrics-app
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
